### ISSUE TITLE
Save data after script execution

### ISSUE THREAD

**Issue by ItsNathanG** [PlaceholderAPI-Expansions/Javascript-Expansion#2]
Currently, the scripts data is saved [whenever the expansion unloads](https://github.com/PlaceholderAPI-Expansions/Javascript-Expansion/blob/b17620cdbf8e801201fcceb7f421817474e9cea7/src/main/java/com/extendedclip/papi/expansion/javascript/JavascriptExpansion.java#L146-L151).

I'm proposing that the data (for the script that is executed) be saved after each script has finished executing, in order to safeguard further against losing data on server/plugin crashes.

**Comment by Banbeucmas** [comment]
Should you remove the saved data upon executing it the next time?

**Comment by extendedclip** [comment]
Save the data any time in your script with

```JAVA
Placeholder.saveData();
```
34a5893b8a0f15e84024ff165d78047457761983
